//info page

GET http://localhost:3001/info

###
//get all persons
GET http://localhost:3001/api/persons

###
//get person by id
GET http://localhost:3001/api/persons/1

###
//delete person by id
DELETE http://localhost:3001/api/persons/5

###
//add new person
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Zoker",
    "number": "012-3456-7890"
}